"""Minimal OpenAI-compatible mock server for verifying the Video Creator LLM stage.

No dependencies beyond the standard library. Serves /v1/chat/completions and returns
a canned scene list whose count matches the requested number of scenes (parsed from
the user prompt's "Produce exactly N scenes." line).

    python plugins/wan2gp-video-creator/tests/mock_llm_server.py [--port 8000] [--reject-json-mode]

Use --reject-json-mode to 400 on requests carrying response_format, exercising the
client's retry-without-json-mode path.
"""

import argparse
import json
import re
from http.server import BaseHTTPRequestHandler, HTTPServer

REJECT_JSON_MODE = False


def _make_scenes(n: int):
    scenes = []
    for i in range(n):
        scenes.append({
            "scene_summary": f"Scene {i + 1} summary.",
            "image_prompt": f"A vivid opening frame for scene {i + 1}, cinematic lighting.",
            "video_prompt": f"Slow dolly-in over the scene {i + 1} frame, gentle motion.",
            "narration_text": f"This is the narration for scene {i + 1}.",
            "tts_prompt": "calm female narrator, warm tone",
        })
    return {"overall_script": "A short demo video generated by the mock server.", "scenes": scenes}


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):
        pass  # quiet

    def _json(self, code, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length) if length else b"{}"
        try:
            req = json.loads(raw)
        except Exception:
            req = {}

        if REJECT_JSON_MODE and req.get("response_format"):
            self._json(400, {"error": {"message": "response_format not supported"}})
            return

        messages = req.get("messages", [])
        user_text = " ".join(m.get("content", "") for m in messages if m.get("role") == "user")

        # Ping path used by test_connection.
        if "single word: OK" in user_text:
            content = "OK"
        else:
            m = re.search(r"Produce exactly (\d+) scenes", user_text)
            n = int(m.group(1)) if m else 3
            content = json.dumps(_make_scenes(n))

        self._json(200, {
            "id": "mock-1",
            "object": "chat.completion",
            "choices": [{"index": 0, "message": {"role": "assistant", "content": content}, "finish_reason": "stop"}],
        })


def main():
    global REJECT_JSON_MODE
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8000)
    ap.add_argument("--reject-json-mode", action="store_true")
    args = ap.parse_args()
    REJECT_JSON_MODE = args.reject_json_mode
    server = HTTPServer(("0.0.0.0", args.port), Handler)
    print(f"Mock OpenAI-compatible server on http://localhost:{args.port}  (reject_json_mode={REJECT_JSON_MODE})")
    print("Point the Video Creator plugin at this Base URL, model name = 'mock'.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.server_close()


if __name__ == "__main__":
    main()
